---
image: registry.pludoni.com/administrators/docker-images/rails-base:v12

stages:
  - test
  - checks
  - deploy

rspec:
  services:
    - 'postgres:9.4'
    - 'redis:3.0'
  script: bin/ci
  stage: test

pronto:
  image: registry.pludoni.com/administrators/docker-images/code-quality:v2
  stage: test
  script: 'run'

bundle_audit:
  stage: checks
  script: |
    gem install bundler-audit
    bundle-audit update
    bundle-audit check -i CVE-2015-9284

deploy:
  image: registry.pludoni.com/administrators/docker-images/deploy:v6
  script: deploy_app product02 hrfilter
  stage: deploy
  environment: production
  only:
    - master
