language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

addons:
  postgresql: 9.6
  firefox: "latest"

rvm:
  - 2.5.3

services: [ redis ]

before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/application.hrfilter.yml config/application.yml
  - yarn
  - "bundle exec rake db:create RAILS_ENV=test"
  - "bundle exec rake db:schema:load RAILS_ENV=test"

script:
  - bundle exec rspec

bundler_args: "--without development production"
